### ISSUE TITLE
Notification on start/stop pull HLS?

### ISSUE THREAD

**Issue by nilopaim** [q191201771/lal#152]
Is there some way of receiving a notification when someone starts/stops to receive HLS stream?

**Comment by q191201771** [comment]
https://github.com/q191201771/lal/blob/master/pkg/logic/server_manager.go#L848
https://github.com/q191201771/lal/blob/master/pkg/hls/server_handler.go

You can start with these codes around.

It's very nice that you are wishing to send PR, but since I would refactor the whole HTTP Notify module when adding HLS notifications, PR may conflict a lot and not be accepted.
Maybe watching the repo continuity and helping us in the feature.

**Comment by nilopaim** [comment]
I'll be watching and I'll help any way I could.

Thanks.

**Comment by q191201771** [comment]
move to #157

**Comment by q191201771** [comment]
This feature has been done, check it out
